/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class net_sourceforge_beanoa_jni_BeanoaJNI */

#ifndef _Included_net_sourceforge_beanoa_jni_BeanoaJNI
#define _Included_net_sourceforge_beanoa_jni_BeanoaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sourceforge_beanoa_jni_BeanoaJNI
 * Method:    write
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_beanoa_jni_BeanoaJNI_write
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_sourceforge_beanoa_jni_BeanoaJNI	
 * Method:    doInjection
 * Signature: (Lfabiojose/beanoa/bean/Customer;)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_beanoa_jni_BeanoaJNI_doInjection
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
